// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectEFWeb.Models;

#nullable disable

namespace ProjectEFWeb.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20231003045434_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectEFWeb.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("636ab663-4d46-4b0d-99c7-17396bd1ba01"),
                            Nombre = "Actividaes pendientes",
                            Peso = 20
                        },
                        new
                        {
                            CategoriaId = new Guid("636ab663-4d46-4b0d-99c7-17396bd1ba02"),
                            Nombre = "Actividaes personales",
                            Peso = 50
                        });
                });

            modelBuilder.Entity("ProjectEFWeb.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("int");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("636ab663-4d46-4b0d-99c7-17396bd1ba10"),
                            CategoriaId = new Guid("636ab663-4d46-4b0d-99c7-17396bd1ba01"),
                            FechaCreacion = new DateTime(2023, 10, 2, 23, 54, 34, 104, DateTimeKind.Local).AddTicks(192),
                            PrioridadTarea = 1,
                            Puntos = 5,
                            Titulo = "Pago servicios publicos"
                        },
                        new
                        {
                            TareaId = new Guid("636ab663-4d46-4b0d-99c7-17396bd1ba11"),
                            CategoriaId = new Guid("636ab663-4d46-4b0d-99c7-17396bd1ba02"),
                            FechaCreacion = new DateTime(2023, 10, 2, 23, 54, 34, 104, DateTimeKind.Local).AddTicks(209),
                            PrioridadTarea = 0,
                            Puntos = 2,
                            Titulo = "Terminar de ver pelicula"
                        });
                });

            modelBuilder.Entity("ProjectEFWeb.Models.Tarea", b =>
                {
                    b.HasOne("ProjectEFWeb.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ProjectEFWeb.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
